wallet:
  path: /path/to/wallet.json # Path to wallet.
  address: NfgHwwTi3wHAS8aFAN243C5vGbkYDpqLHP # Account address. If omitted default one will be used.
  passphrase: pwd # Passphrase to decrypt wallet. If you're using a wallet without a password, place '' here.

pprof:
  enabled: true # Enable pprof.
  address: localhost:8083
prometheus:
  enabled: true # Enable metrics.
  address: localhost:8084

logger:
  level: debug # Log level.

server:
  - address: 0.0.0.0:8080
    tls:
      enabled: false
      cert_file: /path/to/cert
      key_file: /path/to/key
  - address: 0.0.0.0:8081
    tls:
      enabled: false
      cert_file: /path/to/cert
      key_file: /path/to/key

# Nodes configuration.
# This configuration make the gateway use the first node (grpc://s01.neofs.devenv:8080)
# while it's healthy. Otherwise, the gateway use the second node (grpc://s01.neofs.devenv:8080)
# for 10% of requests and the third node for 90% of requests.
peers:
  0:
    # Endpoint.
    address: grpc://s01.neofs.devenv:8080

    # Until nodes with the same priority level are healthy
    # nodes with other priority are not used.
    # The lower the value, the higher the priority.
    priority: 1

    # Load distribution proportion for nodes with the same priority.
    weight: 1
  1:
    address: grpc://s02.neofs.devenv:8080
    priority: 2
    weight: 1
  2:
    address: grpc://s03.neofs.devenv:8080
    priority: 2
    weight: 9


web:
  # Per-connection buffer size for requests' reading.
  # This also limits the maximum header size.
  read_buffer_size: 4096

  # Per-connection buffer size for responses' writing.
  write_buffer_size: 4096

  # ReadTimeout is the amount of time allowed to read
  # the full request including body. The connection's read
  # deadline is reset when the connection opens, or for
  # keep-alive connections after the first byte has been read.
  read_timeout: 10m

  # WriteTimeout is the maximum duration before timing out
  # writes of the response. It is reset after the request handler
  # has returned.
  write_timeout: 5m

  # StreamRequestBody enables request body streaming,
  # and calls the handler sooner when given body is
  # larger then the current limit.
  stream_request_body: true

  # Maximum request body size.
  # The server rejects requests with bodies exceeding this limit.
  max_request_body_size: 4194304

# RPC endpoint to be able to use nns container resolving.
rpc_endpoint: http://morph-chain.neofs.devenv:30333

upload_header:
  use_default_timestamp: false # Create timestamp for object if it isn't provided by header.

connect_timeout: 5s # Timeout to dial node.
stream_timeout: 10s # Timeout for individual operations in streaming RPC.
request_timeout: 5s # Timeout to check node health during rebalance.
rebalance_timer: 30s # Interval to check nodes health.
pool_error_threshold: 100 # The number of errors on connection after which node is considered as unhealthy.

zip:
  compression: false # Enable zip compression to download files by common prefix.
